title: podcasts stories
podcastrss:
  - id: listenastory-journeytothewest
    title: 咕咕老師：西遊記
  - id: listenastory-flowersinthemirror
    title: 咕咕老師：鏡花緣
  - id: 1U_-WsgoDcdisawb-UySWZDvnqEN_bzm1
    title: GK爸爸原創故事繪本

podcasts:
  - id: storytogether
    title: 一起說故事
  - id: storytogether-qiangqiangsadventure
    title: 一起說故事：強強歷險記
  - id: momanddadstory-dinosaurschool
    title: 媽爹講故事-恐龍小學
  - id: momanddadstory-dinosaurschool2
    title: 媽爹講故事-恐龍小學2
  - id: momanddadstory-journeytothewest
    title: 媽爹講故事-媽爹講西遊
  - id: momanddadstory-oz
    title: 媽爹講故事-綠野仙蹤
  - id: momanddadstory-aliceinwonderland
    title: 媽爹講故事-愛麗絲夢遊仙境
  - id: momanddadstory-peterpan
    title: 媽爹講故事-小飛俠彼得潘
  - id: momanddadstory-pinocchio
    title: 媽爹講故事-木偶奇遇記
  - id: momanddadstory-littlesun
    title: 媽爹講故事-小兒子阿甯咕
  - id: momanddadstory-changeworld
    title: 媽爹講故事-那些改變世界的人
  - id: momanddadstory-changeworld2
    title: 媽爹講故事-那些改變世界的人-中華篇
  - id: momanddadstory-idiomstory
    title: 媽爹講故事-成語小故事
  - id: momanddadstory-idiomstory2
    title: 媽爹講故事-成語小故事2
  - id: momanddadstory-timeandspaceadventure
    title: 媽爹講故事-超時空冒險
  - id: momanddadstory-flypiepie
    title: 媽爹講故事-飛翔吧！派派
  - id: momanddadstory-flypiepie2
    title: 媽爹講故事-飛翔吧！派派2
  - id: momanddadstory-flypiepie3
    title: 媽爹講故事-飛翔吧！派派3
  - id: momanddadstory-savehen
    title: 媽爹講故事-飛翔吧！派派-拯救母雞大作戰
  - id: momanddadstory-holiday
    title: 媽爹講故事-飛翔吧！派派-派派fun暑假
  - id: momanddadstory-haqiqi
    title: 媽爹講故事-神探哈奇奇
  - id: dingdangmami
    title: 聽說有故事
  - id: happycar-amos
    title: 維多叔叔的故事歡樂車-艾摩斯偵探事務所
  - id: happycar-joke
    title: 維多叔叔的故事歡樂車-多多與多爸
  - id: happycar-localstory
    title: 維多叔叔的故事歡樂車-民間傳說
  - id: happycar-original
    title: 維多叔叔的故事歡樂車-童話原創
  - id: gk-joke
    title: GK爸爸原創故事繪本-虎哥練笑話
  - id: molodymom-snowwolfboy
    title: 超夢莉媽媽-雪狼男孩
  - id: happythreekingdoms01
    title: 歡樂三國志 01 - 皇帝，快跑！
  - id: happythreekingdoms02
    title: 歡樂三國志 02 - 貂蟬的魔法愛情
  - id: happythreekingdoms03
    title: 歡樂三國志 03 - 那一夜，張飛喝醉了酒
  - id: happythreekingdoms04
    title: 歡樂三國志 04 - 曹操的不倫戀情
  - id: happythreekingdoms05
    title: 歡樂三國志 05 - 聽說關羽投降了
  - id: happythreekingdoms06
    title: 歡樂三國志 06 - 袁紹曹操的麵包戰爭
  - id: happythreekingdoms07
    title: 歡樂三國志 07 - 遇見床上的諸葛亮
  - id: happythreekingdoms08
    title: 歡樂三國志 08 - 趙雲抱娃娃，殺啊！
  - id: happythreekingdoms09
    title: 歡樂三國志 09 - 周瑜胸口永遠的痛
  - id: happythreekingdoms10
    title: 歡樂三國志 10 - 一一九！赤壁失火了
  - id: happythreekingdoms11
    title: 歡樂三國志 11 - 劉備你非娶不可
  - id: happythreekingdoms12
    title: 歡樂三國志 12 - 馬超曾經是超人，但是…
  - id: happythreekingdoms13
    title: 歡樂三國志 13 - 誰害曹操黑眼圈？
  - id: happythreekingdoms14
    title: 歡樂三國志 14 - 關羽最後的安可曲
  - id: happythreekingdoms15
    title: 歡樂三國志 15 - 我決定恨你一萬年
  - id: happythreekingdoms16
    title: 歡樂三國志 16 - 蠻王孟獲的怪獸兵團
  - id: happythreekingdoms17
    title: 歡樂三國志 17 - 司馬懿，你又被騙了
  - id: happythreekingdoms18
    title: 歡樂三國志 18 - 諸葛亮的復活惡作劇
  - id: happythreekingdoms19
    title: 歡樂三國志 19 - 振作啊！活著才能當皇帝
  - id: happythreekingdoms20
    title: 歡樂三國志 20 - 再見英雄
  - id: disney-readalong
    title: Disney Read-Along
  - id: disney-storyette
    title: Disney Storyette
  - id: disney-storyteller
    title: Disney Storyteller
  - id: bettywu-investitureofthegods
    title: 吳淡如：封神榜
  - id: bettywu-journeytothewest
    title: 吳淡如：西遊記
  - id: bettywu-littleprince
    title: 吳淡如：小王子
  - id: bettywu-flowersinthemirror
    title: 吳淡如：鏡花緣
  - id: bettywu-watermargin
    title: 吳淡如：水滸傳
  - id: bettywu-dreamoftheredchamber
    title: 吳淡如：紅樓夢
  - id: bettywu-shakespeare
    title: 吳淡如：莎士比亞
  - id: bettywu-romanceofthethreekingdoms
    title: 吳淡如：三國演義
  - id: bettywu-jinpingmei
    title: 吳淡如：金瓶梅
  - id: bettywu-liaozhai
    title: 吳淡如：緣定逃不了，新浪漫聊齋
  - id: bettywu-theoutlineofchinesehistory
    title: 吳淡如：中國史綱
  - id: bettywu-fivebarbarians
    title: 吳淡如：五胡亂華
  - id: bettywu-shiji
    title: 吳淡如：史記
  - id: bettywu-sudongpo
    title: 吳淡如：行雲流水蘇東坡
  - id: bettywu-goldenquotes
    title: 吳淡如：重啟人生的金句
  - id: bettywu-suntzu
    title: 吳淡如：孫子兵法與商業策略
  - id: bettywu-historicalmystery
    title: 吳淡如-歷史解謎
  - id: bettywu-historicalluminaries
    title: 吳淡如-歷史發光人物
  - id: goodnightmoon-theironmask
    title: 晚安．月亮-鐵假面具
  - id: goodnightmoon-alittleprincess
    title: 晚安．月亮：小公主
  - id: goodnightmoon-animalfarm
    title: 晚安．月亮：動物農莊
  - id: goodnightmoon-aroundtheworldineightydays
    title: 晚安．月亮：環遊世界八十天
  - id: goodnightmoon-donquixote
    title: 晚安．月亮：唐吉訶德
  - id: goodnightmoon-gullivertravels
    title: 晚安．月亮：格列佛遊記
  - id: goodnightmoon-huckleberryfinn
    title: 晚安．月亮：頑童歷險記
  - id: goodnightmoon-kingsolomonsmines
    title: 晚安．月亮：所羅門王的寶藏
  - id: goodnightmoon-littleprince
    title: 晚安．月亮：小王子
  - id: goodnightmoon-nobodysgirl
    title: 晚安．月亮：孤女努力記
  - id: goodnightmoon-olivertwist
    title: 晚安．月亮：孤雛淚
  - id: goodnightmoon-peterpan
    title: 晚安．月亮：小飛俠
  - id: goodnightmoon-pinocchio
    title: 晚安．月亮：木偶奇遇記
  - id: goodnightmoon-robinhood
    title: 晚安．月亮：俠盜羅賓漢
  - id: goodnightmoon-tomsawyer
    title: 晚安．月亮：湯姆歷險記
  - id: goodnightmoon-legendofthewhitesnake
    title: 晚安．月亮：白蛇傳
  - id: goodnightmoon-investitureofthegods
    title: 晚安．月亮：封神傳
  - id: goodnightmoon-storyofaesop
    title: 晚安．月亮：伊索的故事
  - id: goodnightmoon-achristmascarol
    title: 晚安．月亮：聖誕頌歌
  - id: goodnightmoon-frankenstein
    title: 晚安．月亮：科學怪人
  - id: goodnightmoon-thewindonthewillows
    title: 晚安．月亮：柳林中的風聲
  - id: goodnightmoon-amidsummernightsdream
    title: 晚安．月亮：仲夏夜之夢
  - id: goodnightmoon-anneofgreengables
    title: 晚安．月亮：清秀佳人
  - id: goodnightmoon-thephantomoftheopera
    title: 晚安．月亮：歌劇魅影
  - id: goodnightmoon-thethreemusketeers
    title: 晚安．月亮：三劍客
  - id: goodnightmoon-heidi
    title: 晚安．月亮：海蒂
  - id: goodnightmoon-thehollowneedle
    title: 晚安．月亮：亞森羅蘋 - 奇巖城
  - id: goodnightmoon-arsenelupinversusherlocksholmes
    title: 晚安．月亮：亞森羅蘋 - 怪盜與名偵探
  - id: goodnightmoon-lesdentsdutigre
    title: 晚安．月亮：亞森羅蘋 - 虎牙
  - id: goodnightmoon-lesecondvisage
    title: 晚安．月亮：亞森羅蘋 - 雙面人
  - id: goodnightmoon-delabrigademondaine
    title: 晚安．月亮：亞森羅蘋 - 羅蘋的大冒險
  - id: goodnightmoon-leprincedejericho
    title: 晚安．月亮：亞森羅蘋 - 魔人與海盜王
  - id: goodnightmoon-lebouchondecristal
    title: 晚安．月亮：亞森羅蘋 - 玻璃瓶塞的秘密
  - id: sandrastoryshow-journeytothewest
    title: 故事糖果屋：西遊記
  - id: vegatsai-arabiannights
    title: 蔡燦得：天方夜譚
  - id: vegatsai-nobodysgirl
    title: 蔡燦得：小英的故事
  - id: liyanqiu-storytelling
    title: 李豔秋-李豔秋說故事
  - id: unclesun-storytelling
    title: 孫越-孫越叔叔說故事
  - id: yabi-storytelling
    title: 芽比兔-說故事
