title: podcasts stories
podcastrss:
  - id: listenastory-journeytothewest
    title: 咕咕老師：西遊記
  - id: listenastory-flowersinthemirror
    title: 咕咕老師：鏡花緣
podcasts:
  - id: storytogether
    title: 一起說故事
  - id: storytogether-qiangqiangsadventure
    title: 一起說故事：強強歷險記
  - id: momanddadstory-dinosaurschool
    title: 媽爹講故事-恐龍小學
  - id: momanddadstory-oz
    title: 媽爹講故事-綠野仙蹤
  - id: momanddadstory-aliceinwonderland
    title: 媽爹講故事-愛麗絲夢遊仙境
  - id: momanddadstory-peterpan
    title: 媽爹講故事-小飛俠彼得潘
  - id: momanddadstory-pinocchio
    title: 媽爹講故事-木偶奇遇記
  - id: momanddadstory-littlesun
    title: 媽爹講故事-小兒子阿甯咕
  - id: momanddadstory-changeworld
    title: 媽爹講故事-那些改變世界的人
  - id: momanddadstory-changeworld2
    title: 媽爹講故事-那些改變世界的人-中華篇
  - id: momanddadstory-idiomstory
    title: 媽爹講故事-成語小故事
  - id: momanddadstory-idiomstory2
    title: 媽爹講故事-成語小故事2
  - id: momanddadstory-timeandspaceadventure
    title: 媽爹講故事-超時空冒險
  - id: momanddadstory-flypiepie
    title: 媽爹講故事-飛翔吧！派派
  - id: momanddadstory-flypiepie2
    title: 媽爹講故事-飛翔吧！派派2
  - id: momanddadstory-flypiepie3
    title: 媽爹講故事-飛翔吧！派派3
  - id: momanddadstory-savehen
    title: 媽爹講故事-飛翔吧！派派-拯救母雞大作戰
  - id: momanddadstory-holiday
    title: 媽爹講故事-飛翔吧！派派-派派fun暑假
  - id: momanddadstory-haqiqi
    title: 媽爹講故事-神探哈奇奇
  - id: happycar-amos
    title: 維多叔叔的故事歡樂車-艾摩斯偵探事務所
  - id: molodymom-snowwolfboy
    title: 超夢莉媽媽-雪狼男孩
  - id: happythreekingdoms
    title: 歡樂三國志
  - id: disney-readalong
    title: Disney Read-Along
  - id: disney-storyette
    title: Disney Storyette
  - id: disney-storyteller
    title: Disney Storyteller
  - id: bettywu-investitureofthegods
    title: 吳淡如：封神榜
  - id: bettywu-journeytothewest
    title: 吳淡如：西遊記
  - id: bettywu-littleprince
    title: 吳淡如：小王子
  - id: bettywu-flowersinthemirror
    title: 吳淡如：鏡花緣
  - id: bettywu-watermargin
    title: 吳淡如：水滸傳
  - id: bettywu-dreamoftheredchamber
    title: 吳淡如：紅樓夢
  - id: bettywu-shakespeare
    title: 吳淡如：莎士比亞
  - id: bettywu-romanceofthethreekingdoms
    title: 吳淡如：三國演義
  - id: bettywu-jinpingmei
    title: 吳淡如：金瓶梅
  - id: bettywu-liaozhai
    title: 吳淡如：緣定逃不了，新浪漫聊齋
  - id: bettywu-theoutlineofchinesehistory
    title: 吳淡如：中國史綱
  - id: bettywu-fivebarbarians
    title: 吳淡如：五胡亂華
  - id: bettywu-shiji
    title: 吳淡如：史記
  - id: goodnightmoon-alittleprincess
    title: 晚安．月亮：小公主
  - id: goodnightmoon-animalfarm
    title: 晚安．月亮：動物農莊
  - id: goodnightmoon-aroundtheworldineightydays
    title: 晚安．月亮：環遊世界八十天
  - id: goodnightmoon-donquixote
    title: 晚安．月亮：唐吉訶德
  - id: goodnightmoon-gullivertravels
    title: 晚安．月亮：格列佛遊記
  - id: goodnightmoon-huckleberryfinn
    title: 晚安．月亮：頑童歷險記
  - id: goodnightmoon-kingsolomonsmines
    title: 晚安．月亮：所羅門王的寶藏
  - id: goodnightmoon-littleprince
    title: 晚安．月亮：小王子
  - id: goodnightmoon-nobodysgirl
    title: 晚安．月亮：孤女努力記
  - id: goodnightmoon-olivertwist
    title: 晚安．月亮：孤雛淚
  - id: goodnightmoon-peterpan
    title: 晚安．月亮：小飛俠
  - id: goodnightmoon-pinocchio
    title: 晚安．月亮：木偶奇遇記
  - id: goodnightmoon-robinhood
    title: 晚安．月亮：俠盜羅賓漢
  - id: goodnightmoon-tomsawyer
    title: 晚安．月亮：湯姆歷險記
  - id: goodnightmoon-legendofthewhitesnake
    title: 晚安．月亮：白蛇傳
  - id: goodnightmoon-investitureofthegods
    title: 晚安．月亮：封神傳
  - id: goodnightmoon-storyofaesop
    title: 晚安．月亮：伊索的故事
  - id: goodnightmoon-achristmascarol
    title: 晚安．月亮：聖誕頌歌
  - id: goodnightmoon-frankenstein
    title: 晚安．月亮：科學怪人
  - id: goodnightmoon-thewindonthewillows
    title: 晚安．月亮：柳林中的風聲
  - id: goodnightmoon-amidsummernightsdream
    title: 晚安．月亮：仲夏夜之夢
  - id: goodnightmoon-anneofgreengables
    title: 晚安．月亮：清秀佳人
  - id: goodnightmoon-thephantomoftheopera
    title: 晚安．月亮：歌劇魅影
  - id: goodnightmoon-thethreemusketeers
    title: 晚安．月亮：三劍客
  - id: goodnightmoon-heidi
    title: 晚安．月亮：海蒂
  - id: goodnightmoon-thehollowneedle
    title: 晚安．月亮：亞森羅蘋 - 奇巖城
  - id: goodnightmoon-arsenelupinversusherlocksholmes
    title: 晚安．月亮：亞森羅蘋 - 怪盜與名偵探
  - id: goodnightmoon-lesdentsdutigre
    title: 晚安．月亮：亞森羅蘋 - 虎牙
  - id: goodnightmoon-lesecondvisage
    title: 晚安．月亮：亞森羅蘋 - 雙面人
  - id: goodnightmoon-delabrigademondaine
    title: 晚安．月亮：亞森羅蘋 - 羅蘋的大冒險
  - id: goodnightmoon-leprincedejericho
    title: 晚安．月亮：亞森羅蘋 - 魔人與海盜王
  - id: goodnightmoon-lebouchondecristal
    title: 晚安．月亮：亞森羅蘋 - 玻璃瓶塞的秘密
  - id: sandrastoryshow-journeytothewest
    title: 故事糖果屋：西遊記
  - id: vegatsai-arabiannights
    title: 蔡燦得：天方夜譚
  - id: vegatsai-nobodysgirl
    title: 蔡燦得：小英的故事
  - id: midnighttales-thetragedyofv
    title: 午夜奇譚-V的悲劇
  - id: midnighttales-anunsettlingbirthcry
    title: 午夜奇譚-不安的產聲
  - id: midnighttales-2pm
    title: 午夜奇譚-午後兩點的訃文
  - id: midnighttales-nightflight
    title: 午夜奇譚-夜間飛行殺人事件
  - id: midnighttales-corpsemystery
    title: 午夜奇譚-屍謎
  - id: midnighttales-sendai
    title: 午夜奇譚-消失在仙台的女人
  - id: midnighttales-loveletter
    title: 午夜奇譚-情書
  - id: midnighttales-murderousintent
    title: 午夜奇譚-殺意的設計
  - id: midnighttales-latenightcourt
    title: 午夜奇譚-深夜的法庭
  - id: midnighttales-terminal
    title: 午夜奇譚-終點站
  - id: midnighttales-mogamigawa
    title: 午夜奇譚-最上川殺人事件
  - id: midnighttales-cloud
    title: 午夜奇譚-雲上的殺意
  - id: midnighttales-blackwhite
    title: 午夜奇譚-黑白的旅途
  - id: midnighttales-hairstylistmurdercase
    title: 午夜奇譚-髮型設計師殺人事件
  - id: midnighttales-japanesemysterydrama1
    title: 午夜奇譚-日本推理劇1
  - id: midnighttales-japanesemysterydrama2
    title: 午夜奇譚-日本推理劇2
  - id: qingxue-ghostblowsoutthelight
    title: 青雪-鬼吹灯
  - id: aibaoliang-ghostblowsoutthelight1-2
    title: 艾宝良-鬼吹灯1-2
  - id: aibaoliang-ghostblowsoutthelight3-4
    title: 艾宝良-鬼吹灯3-4
  - id: aibaoliang-ghostblowsoutthelight5-8
    title: 艾宝良-鬼吹灯5-8
